name = "exchange-rates-updater"
type = "javascript"
zone_id = ""
route = ""
workers_dev = true
compatibility_date = "2023-01-19"

account_id = "" # Production account
# account_id = "" # Personal Account

[[kv_namespaces]]
binding = "EXCHANGE_RATES"
preview_id = "1f33e36772b74c1e8ec65abf2960f70e"
id = "947f468463f8470fa2d77edb514f7f16"

[vars]
APP_NAME = 'exchange-rates-updater'
ENVIRONMENT_NAME = 'worker'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'cloudflare-workers'
SENTRY_AUTH_TOKEN = ''

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"

[triggers]
crons = ["0 */12 * * *"]
